declare const styles: {
  readonly "clickList": string;
  readonly "clickHeader": string;
  readonly "clickHeaderMain": string;
  readonly "clickHeaderMeta": string;
  readonly "clickTitle": string;
  readonly "attemptTableWrap": string;
  readonly "attemptTable": string;
  readonly "colRank": string;
  readonly "colCandidate": string;
  readonly "colIndexer": string;
  readonly "colProvider": string;
  readonly "colSize": string;
  readonly "colOutcome": string;
  readonly "colReason": string;
  readonly "colDuration": string;
  readonly "attemptCards": string;
  readonly "attemptCardTop": string;
  readonly "attemptIndexer": string;
  readonly "attemptCardTitle": string;
  readonly "attemptCardMeta": string;
  readonly "attemptCardMetaDot": string;
};
export = styles;
